version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    volumes:
      - '/var/lib/elasticsearch:/var/lib/elasticsearch'
    environment:
      - discovery.type=single-node
    ports:
      - '9200:9200'
  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.3
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
      - "5001:5001"
      - "5002:5002"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    environment:
      SERVER_NAME: elasticsearch
    ports:
      - '5601:5601'
